name: jamb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.4
  url_launcher: ^6.3.2
  provider: ^6.1.2
  file_picker: 11.0.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/specialita/
    - assets/brevetti/
    - assets/data/
    - assets/data/obiettivi.json
    - assets/data/transazioni.json
    - assets/data/eventi.json